default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - verify
  - build
  - deploy

lint:
  stage: verify
  script:
    - npm run lint

build:
  stage: build
  needs: []
  script:
    - npm run build:production
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - ci/pages-preparation.sh
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
